src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java, src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/java/WebProject/withpet/common/constants/ErrorCode.java, src/main/java/WebProject/withpet/common/constants/ResponseConstants.java, src/main/java/WebProject/withpet/common/dto/ApiErrorResponse.java, src/main/java/WebProject/withpet/common/exception/DataNotFoundException.java, src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java, src/main/java/WebProject/withpet/common/exception/UnauthorizedException.java, src/main/java/WebProject/withpet/common/exception/UserNotFoundException.java, src/main/java/WebProject/withpet/pets/controller/PetController.java, src/main/java/WebProject/withpet/pets/domain/Pet.java, src/main/java/WebProject/withpet/pets/domain/PetRepository.java, src/main/java/WebProject/withpet/pets/dto/PetRequestDto.java, src/main/java/WebProject/withpet/pets/dto/PetResponseDto.java, src/main/java/WebProject/withpet/pets/service/PetService.java, src/main/java/WebProject/withpet/users/domain/User.java
closed #23 
closed #22 
1. pet 관련 crud 를 구현했습니다.
2. pet crud 의 커스텀 에러 핸들링 기능을 추가했습니다.
3. 로그인과 회원가입을 제외한 request 에 대하여 인터셉터가 토큰의 유효성을 검증하도록 하는 기능을 추가했습니다.
=> pet 관련 기능 구현

.gitignore, scripts/deploy.sh, src/main/resources/application.properties
closed #25 
closed #14 
1. 배포 관련 shell 추가
2. application properties 추가
암호화 하지 않고 jenkins 의 string parameter 를 이용했습니다
[참고자료](https://redcoder.tistory.com/300)
=> CI/CD 관련 세팅

src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java, src/main/java/WebProject/withpet/common/auth/filter/JwtAuthorizationFilter.java, src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java, src/main/java/WebProject/withpet/common/config/WebConfig.java
- 인가 관련 테스트 도중 인가가 제대로 작동하지 않는 버그 발견해서 수정했습니다.
=> fix: 인가 과정 버그 수정

src/main/java/WebProject/withpet/articles/domain/Article.java, src/main/java/WebProject/withpet/common/constants/ErrorCode.java, src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java, src/main/java/WebProject/withpet/users/controller/UserController.java, src/main/java/WebProject/withpet/users/domain/User.java, src/main/java/WebProject/withpet/users/dto/SocialLoginResponseDto.java, src/main/java/WebProject/withpet/users/dto/SocialUserInfoDto.java, src/main/java/WebProject/withpet/users/dto/UserChangeInfoRequestDto.java, src/main/java/WebProject/withpet/users/service/UserService.java
=> feat: 유저 수정 관련 코드 추가

src/main/java/WebProject/withpet/articles/domain/Comment.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/java/WebProject/withpet/users/controller/MypageController.java, src/main/java/WebProject/withpet/users/controller/UserController.java, src/main/java/WebProject/withpet/users/dto/MypageChangeRequestDto.java, src/main/java/WebProject/withpet/users/service/MypageService.java, src/main/java/WebProject/withpet/users/service/UserService.java, src/main/resources/application.properties
=> 마이페이지 리팩토링

src/main/java/WebProject/withpet/pets/controller/PetController.java, src/main/java/WebProject/withpet/users/controller/UserController.java
- 모든 응답이 ResponseEntity의 body에 담기도록 수정했습니다.
=> refactor: 모든 응답이 ResponseEntity의 body에 담기도록 수정

src/main/java/WebProject/withpet/pets/service/PetService.java, src/main/java/WebProject/withpet/users/domain/User.java
- 도메인 단에서 pet 에 대한 접근 및 수정 권한 판단이 이루어지는 것은 책임에 어긋난다고 생각.
- User 도메인에 대한 책임이 불명확해진다고 생각하여 수정
=> pet의 수정 권한 판단 레이어 변경

src/main/java/WebProject/withpet/common/constants/ErrorCode.java, src/main/java/WebProject/withpet/common/dto/ApiErrorResponse.java, src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
1. MethodArgumentNotValidException 에러 발생시 BindingResult 를 통해 어떤 Argument 에서 오류가 나는지 확인할 수 있도록 하는 기능 구현
2. ConstraintViolationException 에러 발생시 어떤 파라미터에서유효성 검사를 통과하지 못하는지 메시지를 응답에 반환해주는 기능 구현
=> BindingResult 를 통한 에러 핸들링 기능 및 ConstraintViolationException 에러 핸들링 기능 추가

src/main/java/WebProject/withpet/pets/domain/Pet.java, src/main/java/WebProject/withpet/pets/dto/PetRequestDto.java
- 상민님의 피드백에 따라 controller 단에서 모든 유효성 검증이 이루어질 수 있도록 도메인에서 dto 로 유효성 조건 관련 부분을 이동했습니다.
=> refactor: pet 의 유효성 검증이 dto 에서 이루어지도록 수정

src/main/java/WebProject/withpet/users/dto/UserRequestDto.java
- user 회원가입의 유효성 검증이 dto 에서 이루어지도록 수정
=> refactor: user 회원가입의 유효성 검증이 dto 에서 이루어지도록 수정

src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java
closed #41 
- jenkins 파라미터 세팅에 토큰 관련 시크릿키 세팅을 하고, 소스코드에서는 해당 부분을 숨겼습니다.
=> chore: 토큰 관련 암호화 세팅

src/main/java/WebProject/withpet/challenges/controller/ChallengeController.java, src/main/java/WebProject/withpet/challenges/domain/Challenge.java, src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/resources/application.properties
- 프로퍼티를 읽어들이는 과정에서 오류가 발생해 해당 오류를 해결했습니다.
=> fix: 프로퍼티를 읽어들이는 과정 오류 해결

src/main/java/WebProject/withpet/articles/controller/ArticleController.java, src/main/java/WebProject/withpet/common/config/WebConfig.java
1. 게시글 생성할때 사진이 없어도 생성이 가능하도록 코드 변경
2. CORS 에러 해결을 위한 addCorsMappings 메소드 override
=> 게시글 생성 수정 및 CORS 에러 해결을 위한 설정 추가

src/main/java/WebProject/withpet/common/config/WebConfig.java
=> feat: CORS 문제 해결을 위한 헤더 설정 추가

src/main/java/WebProject/withpet/common/config/SecurityConfig.java
feat: CORS 문제 해결을 위한 시큐리티 설정 추가
=> feat: CORS 문제 해결을 위한 설정 추가

src/main/java/WebProject/withpet/common/config/SecurityConfig.java, src/main/java/WebProject/withpet/common/config/WebConfig.java
CORS 버그 해결을 위한 시큐리티 설정 변경
시큐리티 설정 추가 했는데 화요일날 확인해 주세요~. 지금 프론트랑 api 테스트를 위해서 머지 하겠습니다.
=> CORS 버그 해결을 위한 시큐리티 설정 변경

src/main/java/WebProject/withpet/common/auth/application/JwtTokenProvider.java, src/main/java/WebProject/withpet/common/auth/filter/JwtAuthorizationFilter.java, src/main/java/WebProject/withpet/common/config/JwtAuthInterceptor.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/java/WebProject/withpet/common/constants/ErrorCode.java, src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java, src/main/java/WebProject/withpet/common/util/JwtUtil.java
1. 인터셉터가 필요없는 패턴 삭제
2. 토큰 관련 util 클래스 생성 및 메서드 구현
3. 예외 발생 시 응답 형태 지정
=> feat: 토큰 유효성 검사 관련 기능 구현 

src/main/java/WebProject/withpet/articles/controller/ArticleController.java, src/main/java/WebProject/withpet/challenges/controller/ChallengeController.java, src/main/java/WebProject/withpet/common/constants/ResponseConstants.java, src/main/java/WebProject/withpet/common/constants/ResponseMessages.java, src/main/java/WebProject/withpet/pets/controller/PetController.java, src/main/java/WebProject/withpet/users/controller/MypageController.java
1. 자주 사용되는 문자열을 상수로 리팩토링 했습니다.
=> refactor: 자주 사용되는 문자열 상수로 리팩토링

src/main/java/WebProject/withpet/pets/domain/ConsumptionRepositoryImpl.java, src/main/java/WebProject/withpet/pets/dto/ConsumptionRequestDto.java, src/main/java/WebProject/withpet/pets/dto/ConsumptionResponseDto.java, src/main/java/WebProject/withpet/pets/dto/MonthlyConsumptionByUserResponseDto.java
=> refactor: 가계부 dto에 빠진 컬럼 추가

src/main/java/WebProject/withpet/articles/controller/ArticleController.java, src/main/java/WebProject/withpet/articles/controller/ArticleLikeController.java, src/main/java/WebProject/withpet/articles/domain/Article.java, src/main/java/WebProject/withpet/articles/domain/ArticleLike.java, src/main/java/WebProject/withpet/articles/domain/Filter.java, src/main/java/WebProject/withpet/articles/domain/SpecArticle.java, src/main/java/WebProject/withpet/articles/dto/ArticleLikeRequestDto.java, src/main/java/WebProject/withpet/articles/dto/ArticleUpdateRequestDto.java, src/main/java/WebProject/withpet/articles/dto/ViewArticleListDto.java, src/main/java/WebProject/withpet/articles/dto/ViewArticleListRequestDto.java, src/main/java/WebProject/withpet/articles/repository/ArticleLikeRepository.java, src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryCustom.java, src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryImpl.java, src/main/java/WebProject/withpet/articles/service/ArticleLikeService.java, src/main/java/WebProject/withpet/articles/service/ArticleService.java, src/main/java/WebProject/withpet/articles/service/ImageService.java, src/main/java/WebProject/withpet/articles/validation/ArticleCreateValidator.java, src/main/java/WebProject/withpet/articles/validation/ArticleScrollDownValidator.java, src/main/java/WebProject/withpet/comments/controller/CommentController.java, src/main/java/WebProject/withpet/comments/dto/CreateCommentRequestDto.java, src/main/java/WebProject/withpet/comments/service/CommentService.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/java/WebProject/withpet/common/constants/ErrorCode.java, src/main/java/WebProject/withpet/common/exception/ArticleException.java, src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java, src/main/java/WebProject/withpet/common/exception/UnauthorizedException.java, src/main/java/WebProject/withpet/users/service/UserService.java, src/test/java/WebProject/withpet/comment/CommentServiceTest.java
현재 프론트 api 테스트 중 게시글 생성 관련 에러로 인해 작성코드 일단 머지하고 추후 나머지 api 코드 구현한 다음에 다시 pr할때 관련 세부사항 적겠습니다!
=> 게시글 생성 관련 에러로 인해 작성코드 일단 머지하고 추후 다시 pr할때 관련 세부사항 적겠습니다

src/main/java/WebProject/withpet/articles/controller/ArticleController.java, src/main/java/WebProject/withpet/articles/controller/ImageController.java, src/main/java/WebProject/withpet/articles/domain/Article.java, src/main/java/WebProject/withpet/articles/dto/ArticleUpdateRequestDto.java, src/main/java/WebProject/withpet/articles/dto/ImageDto.java, src/main/java/WebProject/withpet/articles/service/ArticleService.java, src/main/java/WebProject/withpet/articles/service/ImageService.java, src/main/java/WebProject/withpet/comments/repository/CommentRepository.java, src/main/java/WebProject/withpet/comments/service/CommentService.java, src/main/java/WebProject/withpet/common/file/AwsS3Service.java
EC2 QueryDsl 컴파일 오류가 나와서 현재 작성 중인 코드를 일반 master에 푸시하고자 합니다. 추후 리뷰 부탁드려요
1. 게시글 수정 api 관련 코드 작성(미완성)
2. 이미지 삭제 api 삭제에 따른 관련 코드 삭제
3. 이미지 URL로부터 파일 이름 추출 > S3에서 해당 파일 이름의 이미지 삭제
=> 이미지 삭제 api의 삭제에 따른 코드 수정 및 삭제

build.gradle, src/main/java/WebProject/withpet/auth/controller/EmailController.java, src/main/java/WebProject/withpet/auth/domain/ConfirmationToken.java, src/main/java/WebProject/withpet/auth/domain/ConfirmationTokenRepository.java, src/main/java/WebProject/withpet/auth/service/ConfirmationTokenService.java, src/main/java/WebProject/withpet/auth/service/EmailService.java, src/main/java/WebProject/withpet/auth/service/EmailServiceImpl.java, src/main/java/WebProject/withpet/auth/util/ConfirmationKey.java, src/main/java/WebProject/withpet/common/config/EmailConfig.java, src/main/java/WebProject/withpet/common/constants/ErrorCode.java, src/main/java/WebProject/withpet/users/service/UserService.java
closed #66 
1. 이메일 관련 세팅
2. 이메일 전송 기능
3. 랜덤 확인 코드 생성 기능
4. 이메일 코드 확인 및 권한 확인 기능 구현
=> feat: 이메일 전송 기능 구현

src/main/java/WebProject/withpet/common/config/SecurityConfig.java
- 로그인 커스터마이징 시에 사용되지 않는 세팅을 해둬서 이를 삭제했습니다.
- 탈퇴가 제대로 동작하는 것을 확인했습니다.
=> fix: 로그인 관련 필요하지 않은 세팅 제거

src/main/java/WebProject/withpet/common/config/SecurityConfig.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/java/WebProject/withpet/users/controller/UserController.java, src/main/java/WebProject/withpet/users/dto/ChangePasswordDto.java, src/main/java/WebProject/withpet/users/service/UserService.java
1. 로그인 하지 않아도 비밀번호 수정 가능하도록 수정했습니다.
2. 카카오 로그인 시 access token뿐만 아니라 refresh token도 헤더에 반환되도록 수정하였습니다.
=> 비밀번호 변경 코드 수정, 카카오 소셜 로그인 시 refresh token 반환

src/main/java/WebProject/withpet/challenges/domain/Challenge.java, src/main/java/WebProject/withpet/pets/domain/Pet.java, src/main/java/WebProject/withpet/users/domain/User.java
=> feat: pet, user 양방향 관계 설정

src/main/java/WebProject/withpet/pets/controller/DiaryController.java, src/main/java/WebProject/withpet/pets/domain/Diary.java, src/main/java/WebProject/withpet/pets/domain/DiaryRepository.java, src/main/java/WebProject/withpet/pets/domain/DiaryRepositoryCustom.java, src/main/java/WebProject/withpet/pets/domain/DiaryRepositoryImpl.java, src/main/java/WebProject/withpet/pets/domain/HealthCare.java, src/main/java/WebProject/withpet/pets/domain/HealthCareRepositoryImpl.java, src/main/java/WebProject/withpet/pets/domain/Pet.java, src/main/java/WebProject/withpet/pets/dto/DiaryRequestDto.java, src/main/java/WebProject/withpet/pets/dto/DiaryResponseDto.java, src/main/java/WebProject/withpet/pets/dto/DiaryUpdateDto.java, src/main/java/WebProject/withpet/pets/dto/HealthCareRequestDto.java, src/main/java/WebProject/withpet/pets/dto/HealthCareResponseDto.java, src/main/java/WebProject/withpet/pets/service/DiaryService.java
1. 다이어리를 건강관리 기능에서 분리했습니다.
2. 다이어리의 crud 를 별도로 만들었습니다.
=> refactor: 다이어리를 건강관리 기능과 분리

src/main/java/WebProject/withpet/challenges/domain/Challenge.java, src/main/java/WebProject/withpet/common/config/SecurityConfig.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/java/WebProject/withpet/pets/domain/Pet.java, src/main/java/WebProject/withpet/users/domain/User.java, src/main/java/WebProject/withpet/users/service/UserService.java
1. 카카오 소셜 로그인 과정에서 발생한 UserNotFoundException 문제 해결 >> 소셜 로그인에서는 login()메소드의 
```java
if (!passwordEncoder.matches(password, principalDetails.getPassword())) {
throw new UserNotFoundException();
}
```
부분이 필요 없어 해당 부분 삭제한 메소드 추가
=> 소셜 로그인 UserNotFoundException 문제 해결

src/main/java/WebProject/withpet/articles/dto/ViewArticleDto.java, src/main/java/WebProject/withpet/articles/dto/ViewArticleListResponseDto.java, src/main/java/WebProject/withpet/articles/dto/ViewSpecificArticleResponseDto.java, src/main/java/WebProject/withpet/articles/repository/ArticleLikeRepository.java, src/main/java/WebProject/withpet/articles/repository/ArticleLikeRepositoryCustom.java, src/main/java/WebProject/withpet/articles/repository/ArticleLikeRepositoryImpl.java, src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryImpl.java, src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryPagingCustomImpl.java, src/main/java/WebProject/withpet/articles/service/ArticleService.java, src/main/java/WebProject/withpet/common/config/WebConfig.java, src/main/java/WebProject/withpet/users/service/UserService.java
1. 조인 쿼리 오류로 nonuniqueresultexception 발생해 해당 문제 해결했습니다.
2. 게시글 리스트 조회 시 결과가 없으면 빈 리스트를 반환하도록 수정했습니다.
=> nonuniqueresultexception문제 발생 해결, 게시글 조회 반환 수정

src/main/java/WebProject/withpet/articles/dto/ArticleUpdateRequestDto.java, src/main/java/WebProject/withpet/articles/service/ArticleService.java
1. 변수 네이밍 수정
2. 특정 태그 게시물 수정 안 되는 오류 해결
=> 게시물 수정 api 오류 해결

src/main/java/WebProject/withpet/common/config/SecurityConfig.java, src/main/java/WebProject/withpet/common/system/AwsHealthCheck.java
1. aws target group health check 용 코드 추가
=> aws target group health check 용 코드 추가

src/main/java/WebProject/withpet/users/controller/UserController.java, src/main/java/WebProject/withpet/users/dto/SocialLoginRequestDto.java, src/main/java/WebProject/withpet/users/service/UserService.java, src/main/java/WebProject/withpet/users/service/UserSocialService.java
1. 동적인 redirect URI 정보를 프론트 요청에서 받도록 코드를 수정하였습니다.
=> 소셜 로그인 redirect URI 요구사항 수정

src/main/java/WebProject/withpet/articles/repository/ArticleRepositoryImpl.java, src/main/java/WebProject/withpet/users/controller/UserController.java
api 테스트를 위해 먼저 머지합니다. 추후에 확인 부탁드려요!
1. 404에러 해결
2.  정렬조건 추가
=> 404에러 해결, 정렬조건 추가

src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepository.java, src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepositoryCustom.java, src/main/java/WebProject/withpet/challenges/domain/ChallengeLogRepositoryImpl.java, src/main/java/WebProject/withpet/challenges/domain/ChallengeRepository.java, src/main/java/WebProject/withpet/challenges/domain/ChallengeRepositoryCustom.java, src/main/java/WebProject/withpet/challenges/domain/ChallengeRepositoryImpl.java, src/main/java/WebProject/withpet/challenges/service/ChallengeLogService.java, src/main/java/WebProject/withpet/challenges/service/ChallengeService.java, src/main/java/WebProject/withpet/common/constants/ErrorCode.java, src/main/java/WebProject/withpet/common/exception/DuplicateDateException.java, src/main/java/WebProject/withpet/common/exception/GlobalExceptionHandler.java
- 챌린지명 중복 시 에러 반환
- 챌린지 로그의 날짜 중복 시 에러 반환
=> feat: 챌린지/챌린지 로그의 중복확인 및 에러핸들링 기능 구현
